### ISSUE TITLE
Would you create camel case method names?

### ISSUE THREAD

**Issue by JackKuo-tw** [yiyu0x/line-notify-sdk-nodejs#7]
Most JavaSript naming conventions use camel case instead of snake case.

Would you please add camel case method names to this project? 

Considering the backward compatibility, let both styles exist is a better way.

**Comment by yiyu0x** [comment]
I think it's a good suggestion. Maybe someone can contribute to this project.

**Comment by yiyu0x** [comment]
Hi @WolffParkinson,
Do you want to contribute to this issue? You are keen on this project. I appreciate it.
