### ISSUE TITLE
Superfluous param `client_secret` in `get_token_by_code()` 

### ISSUE THREAD

**Issue by JackKuo-tw** [yiyu0x/line-notify-sdk-nodejs#8]
The constructor has set `client_secret`, why does `get_token_by_code()` need to set it again?

**Comment by yiyu0x** [comment]
Sorry. I don't know what you mean to set it again. I just saw `get_token_by_code` use the argument `client_secret`. Maybe you can show me which line you are confusing.

**Comment by WolffParkinson** [comment]
I think he means [here](https://github.com/yiyu0x/line-notify-sdk-nodejs/blob/06cfe60d0527f2949a9e1a9f4f8aee186aeb0884/line-notify-sdk.js#L56)
